## Erick Pineda Amézquita
## 17012140 
##             Numpy, Matrix y Ndarray ## 


## -----------------
#### Diferencias:


Cuando se utiliza la librería Numpy, el procesamiento de multiples dimensiones se puede realizar por medio de Matrix o de Ndarray. 
La clase general es "ndarray", por lo que "matrix" es una clase heredada de "ndarray".
La diferencia es que "matrix" es específicamente para dos dimensiones, incluyendo algunos métodos de "ndarray" como la transpueta, mientras que "ndarray" sirve para múltiples dimensiones, es decir que soporte mas de 2 dimensiones, por eso se llama "n" "dimension" "array".
Un dato importante, es que no se recomienda utilizar "matrix" ya que la clase puede ser removida en versiones futuras de python.

Parametros de ndarray: ¶
class numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)¶


Parametros de matrix: ¶
class numpy.matrix(data, dtype=None, copy=True)¶




In [2]:
import numpy as np

In [7]:
## Creacion de matrices Numpy:

myMatrix= np.matrix('1 2 3 4 5;6 7 8 9 10')
myMatrix

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [20]:
## Creacion de un arreglo multidimensional:

## Crear un arreglo de 10 elementos
myNDarray = np.array([[1,2,3,4,5],[6,7,8,9,10]], np.int32) 
print(myNDarray)

# Verificar el tipo, notar que es un ndarray
print(type(myNDarray))   

print(myNDarray.ndim)    # Consultamos el número de dimensiones
print(myNDarray.shape)   # Consultamos la dimensión
print(myNDarray.size)   

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
(2, 5)
10


In [25]:
## Traspuesta de la matriz

myMatrix.T



matrix([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]])

In [29]:
## Traspuesta del ndarray
myNDarray.T


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [38]:
## un arreglo con decimales
myNDarrayMulti = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]], np.float) 
myNDarrayMulti


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])